url: "kemett-art.com" # the base hostname & protocol for your site, e.g. http://example.com
title: "Kemett Art" # the name of your site, e.g. ACME Corp.

collections:
  pages:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: "default"

  - scope:
      path: ""
      type: "pages"
    values:
      permalink: "/:path"
      layout: "default"

  - scope:
      path: ""
      type: "posts"
    values:
      permalink: "/portfolio/:categories/:year-:month-:day-:title"
      layout: "post"

exclude:
  - "*readme.md"
