url: "kemett-art.com" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "" # the name of your site, e.g. ACME Corp.

collections:
  pages:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: "default"

  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

exclude:
  - "*readme.md"
